stages:
  - test

percy:
  stage: test
  image: mcr.microsoft.com/playwright:v1.59.1-noble
  script:
    - npm ci
    - npx percy exec --config .percy.yml -- npx playwright test --reporter=dot --grep '@visual-test'
  variables:
    PERCY_CLIENT_API_URL: https://staging.percy.dev/api/v1
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
